version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    container_name: app
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run build && npm start"

  db:
    image: mongo:4.4
    container_name: db
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MONGODB_URL=mongodb+srv://${DB_USER}:${DB_PASSWORD}@cluster0.ingyz5d.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
